# Assignment 1 (Introduction to Python) - (5 Pts)

In this homework, we will go through basic linear algebra, NumPy, and image manipulation using Python to get everyone on the same page for the prerequisite skills for this class.

One of the aims of this homework assignment is to get you to start getting comfortable searching for useful library functions online. So in many of the functions you will implement, you will have to look up helper functions.

## Conda Setup

Generate the conda environment by running in the terminal:

`conda create --name gcv_exercise_1 python=3.11`

Run to activate environment:

`conda activate gcv_exercise_1`

Install all required packages for this exercise by running:

`conda install matplotlib numpy scikit-image pillow`

Install Jupyter Notebook requirements (VSCode may ask you to do this automatically):

`conda install -n gcv_exercise_1 ipykernel --update-deps --force-reinstall`

## Notebook Setup & Imports

In [1]:
# Setup

# The Random module implements pseudo-random number generators
import random 

# Numpy is the main package for scientific computing with Python. 
# This will be one of our most used libraries in this class
import numpy as np

# The Time library helps us time code runtimes
import time

# Import the PIL library, useful for handling images
from PIL import Image

# Matplotlib is a useful plotting library for python 
import matplotlib.pyplot as plt

# This code is to make matplotlib figures appear inline in the
# notebook rather than in a new window.
%matplotlib inline
plt.rcParams['figure.figsize'] = (10.0, 8.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

## Part 1: Linear Algebra and NumPy Review
In this section, we will review linear algebra and learn how to use vectors and matrices in python using numpy. By the end of this section, you will have implemented all the `TODOs`.

## Question 1.1 (0.5 Pt)
First, let's test whether you can define the following matrices and vectors using numpy. Look up `np.array()` for help. In the next code block, define $M$ as a $(4, 3)$ matrix, $a$ as a $(1, 3)$ row vector and $b$ as a $(3, 1)$ column vector:

$$M = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
10 & 11 & 12 \end{bmatrix}
$$

$$a = \begin{bmatrix}
1 & 5 & 0
\end{bmatrix}
$$

$$b = \begin{bmatrix}
-3 \\ 2 \\ 5
\end{bmatrix}  
$$ 

In [ ]:
# *****BEGINNING OF YOUR CODE (DO NOT DELETE THIS LINE)*****
pass
M = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a = np.array([[1,5,0]])
b = np.array([[-3],[2],[5]])
# DOC: https://numpy.org/devdocs//reference/generated/numpy.array.html
# *****END OF YOUR CODE (DO NOT DELETE THIS LINE)*****

print("M = \n", M)
print("The size of M is: ", M.shape)
print()
print("a = ", a)
print("The size of a is: ", a.shape)
print()
print("b = ", b)
print("The size of b is: ", b.shape)

M = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
The size of M is:  (4, 3)

a =  [[1 5 0]]
The size of a is:  (1, 3)

b =  [[-3]
 [ 2]
 [ 5]]
The size of b is:  (3, 1)


## Question 1.2 (1 Pt)
Implement the `dot_product()` method and check that it returns the correct answer for $a^Tb$.

In [5]:
# Now, let's test out this dot product. Your answer should be [[7]].

def dot_product(a, b):
    """Implement dot product between the two vectors: a and b.
    (optional): While you can solve this using for loops, we recommend
    that you look up `np.dot()` online and use that instead.
    Args:
        a: numpy array of shape (x, n)
        b: numpy array of shape (n, x)
    Returns:
        out: numpy array of shape (x, x) (scalar if x = 1)
    """
    out = None
    # *****BEGINNING OF YOUR CODE (DO NOT DELETE THIS LINE)*****
    pass
    # DOC: https://numpy.org/doc/stable/reference/generated/numpy.dot.html
    out = np.dot(a, b)
    # *****END OF YOUR CODE (DO NOT DELETE THIS LINE)*****
    return out
    
aDotB = dot_product(a, b)
print(aDotB)

print("The size is: ", aDotB.shape)

[[7]]
The size is:  (1, 1)


## Question 1.3 (1 Pts)
Implement the `complicated_matrix_function()` method and use it to compute $(ab)Ma^T$

IMPORTANT NOTE: The `complicated_matrix_function()` method expects all inputs to be two dimensional numpy arrays, as opposed to 1-D arrays.  This is an important distinction, because 2-D arrays can be transposed, while 1-D arrays cannot.

To transpose a 2-D array, you can use the syntax `array.T` 

In [7]:
def complicated_matrix_function(M, a, b):
    """Implement (a * b) * (M * a.T).
    (optional): Use the `dot_product(a, b)` function you wrote above
    as a helper function.
    Args:
        M: numpy matrix of shape (m, n).
        a: numpy array of shape (1, n).
        b: numpy array of shape (n, 1).
    Returns:
        out: numpy matrix of shape (m, 1).
    """
    out = None
    # *****BEGINNING OF YOUR CODE (DO NOT DELETE THIS LINE)*****
    pass
    c = dot_product(a, b)
    d = np.dot(M, a.T)
    out = c * d
    # *****END OF YOUR CODE (DO NOT DELETE THIS LINE)*****
    return out

# Your answer should be $[[77], [203], [329], [455]]$ of shape(4, 1).
ans = complicated_matrix_function(M, a, b)
print(ans)
print()
print("The size is: ", ans.shape)

[[ 77]
 [203]
 [329]
 [455]]

The size is:  (4, 1)


# Part 2: Image Manipulation 

Now that you are familiar with using matrices and vectors. Let's load some images and treat them as matrices and do some operations on them.

In [9]:
image1_path = './example.jpg'

def display(img):
    # Show image
    plt.figure(figsize = (5,5))
    plt.imshow(img)
    plt.axis('off')
    plt.show()

## Question 2.1 (0.5 Pt)
Implement the `load()` method and check out the display method above. We will use these two methods through the rest of the notebook to visualize our work.

In [ ]:
def load(image_path):
    """Loads an image from a file path.
    HINT: Look up `PIL: Image.open()` function.
    Args:
        image_path: file path to the image.
    Returns:
        out: numpy array of shape(image_height, image_width, 3).
    """
    out = None

    # Use PIL Image.open
    # *****BEGINNING OF YOUR CODE (DO NOT DELETE THIS LINE)*****
    pass
    image = Image.open(image_path)
    out = np.array(image)
    # *****END OF YOUR CODE (DO NOT DELETE THIS LINE)*****
    # Let's convert the image to be between the correct range.
    out = out.astype(np.float64) / 255
    return out

image1 = load(image1_path)
display(image1)
print(image1.shape)

## Question 2.2 (1 Pts)
One of the most common operations we perform when working with images is rectangular **cropping**, or the action of removing unwanted outer areas of an image.

Take a look at this code we've written to crop out everything but the reader's desk:

In [ ]:
display(image1[540:1080, 540:1080, :])

Implement the `crop_image()` method by taking in the starting row index, starting column index, number of rows, and number of columns, and outputting the cropped image. Do NOT use the PIL library, instead everything can be done only using numpy.

Then, in the cell below, see if you can pull out a 100x100 square from each corner of the original `image1`: the top left, top right, bottom left, and bottom right.

In [ ]:
def crop_image(image, start_row, start_col, num_rows, num_cols):
    """Crop an image based on the specified bounds.
    Args:
        image: numpy array of shape(image_height, image_width, 3).
        start_row (int): The starting row index we want to include in our cropped image.
        start_col (int): The starting column index we want to include in our cropped image.
        num_rows (int): Number of rows in our desired cropped image.
        num_cols (int): Number of columns in our desired cropped image.
    Returns:
        out: numpy array of shape(num_rows, num_cols, 3).
    """

    out = None

    # *****BEGINNING OF YOUR CODE (DO NOT DELETE THIS LINE)*****
    pass
    # *****END OF YOUR CODE (DO NOT DELETE THIS LINE)*****

    return out

r, c = image1.shape[0], image1.shape[1]

top_left_corner = crop_image(image1, 0, 0, 100, 100)
top_right_corner = crop_image(image1, 0, c-100, 100, 100) 
bottom_left_corner = crop_image(image1, r-100, 0, 100, 100)
bottom_right_corner = crop_image(image1, r-100, c-100, 100, 100) 

display(top_left_corner)
display(top_right_corner)
display(bottom_left_corner)
display(bottom_right_corner)

## Question 2.3 (1 Pts)
Let's try another commonly used operation: image resizing!

At a high level, image resizing should go something like this:

1. We create an (initially empty) output array of the desired size, `output_image`
2. We iterate over each pixel position `(i,j)` in the output image
    - For each output pixel, we compute a corresponding input pixel `(input_i, input_j)`
    - We assign `output_image[i, j, :]` to `input_image[input_i, input_j, :]`
3. We return the resized output image

We want `input_i` and `input_j` to increase proportionally with `i` and `j` respectively:

- `input_i` can be computed as `int(i * row_scale_factor)`
- `input_j` can be computed as `int(j * col_scale_factor)`

...where `int()` is a Python operation that takes a float and rounds it down to the nearest integer, and `row_scale_factor` and `col_scale_factor` are constants computed from the image input/output sizes.

Again, do NOT use the PIL library, instead everything can be done using numpy.

Try to figure out what `row_scale_factor` and `col_scale_factor` should be, then implement this algorithm in the `resize_image()` method! Then, run the cells below to test out your image resizing algorithm!

When you downsize the image to 16x16, you should expect an output that looks something like this:

![16_16_desk.png](16_16_desk.png)

When you stretch it horizontally to 50x400, you should get:

![50_400_desk.png](50_400_desk.png)

In [ ]:
def resize_image(input_image, output_rows, output_cols):
    """Resize an image using the nearest neighbor method.
    Args:
        input_image (np.ndarray): RGB image stored as an array, with shape
            `(input_rows, input_cols, 3)`.
        output_rows (int): Number of rows in our desired output image.
        output_cols (int): Number of columns in our desired output image.
    Returns:
        np.ndarray: Resized image, with shape `(output_rows, output_cols, 3)`.
    """
    input_rows, input_cols, channels = input_image.shape
    assert channels == 3

    # 1. Create the resized output image
    output_image = np.zeros(shape=(output_rows, output_cols, 3))

    # 2. Populate the `output_image` array using values from `input_image`
    #    > This should require two nested for loops!
    # *****BEGINNING OF YOUR CODE (DO NOT DELETE THIS LINE)*****
    pass
    # *****END OF YOUR CODE (DO NOT DELETE THIS LINE)*****

    # 3. Return the output image
    return output_image

display(resize_image(image1, 16, 16))
display(resize_image(image1, 50, 400))